### ISSUE TITLE
Marshmallow.ValidationError when loading into Emissor UI

### ISSUE THREAD

**Issue by Tomaati** [tae898/multimodal-datasets#3]
Dear Taewoon,

I hope this is the correct place to ask, but whenever I try to load in the data (CarLani, or example_data in Emissor repo) into the Emissor UI, through Docker or Python I get the following error:

```
Traceback (most recent call last):
  File "/home/tomaati/emissor/venv/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/tomaati/emissor/venv/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/tomaati/emissor/venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/tomaati/emissor/venv/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/tomaati/emissor/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/tomaati/emissor/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/tomaati/emissor/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/tomaati/emissor/venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/tomaati/emissor/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/tomaati/emissor/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/tomaati/emissor/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/tomaati/emissor/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/tomaati/emissor/emissor/annotation/endpoint.py", line 170, in load_signals
    signals = backend.load_modality(scenario_id, Modality[modality.upper()])
  File "/home/tomaati/emissor/emissor/annotation/backend.py", line 56, in load_modality
    ctrl.load_signals(modalities=[modality])
  File "/home/tomaati/emissor/emissor/persistence/persistence.py", line 53, in load_signals
    signals = self._storage.load_modality(self.scenario.id, modality)
  File "/home/tomaati/emissor/emissor/persistence/persistence.py", line 135, in load_modality
    return unmarshal(json_file.read(), cls=cls)
  File "/home/tomaati/emissor/emissor/representation/util.py", line 218, in unmarshal
    return _unmarshal(json_string, cls=cls)
  File "/home/tomaati/emissor/emissor/representation/util.py", line 232, in _unmarshal
    return schema.load(mapping, unknown=marshmallow.EXCLUDE, many=is_collection)
  File "/home/tomaati/emissor/venv/lib/python3.8/site-packages/marshmallow_dataclass/__init__.py", line 628, in load
    all_loaded = super().load(data, many=many, **kwargs)
  File "/home/tomaati/emissor/venv/lib/python3.8/site-packages/marshmallow/schema.py", line 725, in load
    return self._do_load(
  File "/home/tomaati/emissor/venv/lib/python3.8/site-packages/marshmallow/schema.py", line 907, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {0: {'text': ['Missing data for required field.'], 'modality': ['Invalid enum member text']}, 1: {'text': ['Missing data for required field.'], 'modality': ['Invalid enum member text']}, 2: {'text': ['Missing data for required field.'], 'modality': ['Invalid enum member text']}}
```

The scenarios show up, but after clicking one the exception is thrown and nothing happens. Am I missing some data? I used the data obtained after running `annotate-emissor.py` and the example_data from the emissor repo, but all give the same issue.

Thanks in advance!

**Comment by tae898** [comment]
Hi there,

I guess you encountered this problem while running the EMISSOR?

If you don't mind, can you post the issue in the [EMISSOR github repo](https://github.com/leolani/emissor)?

**Comment by Tomaati** [comment]
Ah sorry, moved it there!
